project_id = "evorhaatkaasludhlmeu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-report]
verify_jwt = false

[functions.scrape-coffee-price]
verify_jwt = false

[functions.scrape-coffee-price-yfinance]
verify_jwt = false

[functions.scrape-sugar-price]
verify_jwt = false

[functions.scrape-cocoa-price]
verify_jwt = false

[functions.scrape-butter-price]
verify_jwt = false

[functions.scrape-wheat-price]
verify_jwt = false