// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evorhaatkaasludhlmeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2b3JoYWF0a2Fhc2x1ZGhsbWV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzM3NDIsImV4cCI6MjA3MTg0OTc0Mn0.Eg2aH3AcEc7OzjlWjDH0KQ-uJC4PPGT9NaRgmC1epiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});